server:
  port: 5001

spring:
  jpa:
    database-platform: org.hibernate.dialects.MySQLBDialect
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bankAccount?createDatabaseIfNotExists=true
    username: root
    password: root

  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumero
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serialization.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
